[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mycroft-classic-listener"
dynamic = ["version"]
description = "ovos-core listener daemon client (classic Mycroft implementation)"
readme = "README.md"
license = "Apache-2.0"
requires-python = ">=3.10"

dependencies = [
    "PyAudio~=0.2",
    "ovos-plugin-manager>=2.5.0a1,<3.0.0",
    "ovos-utils>=0.8.4,<1.0.0",
    "ovos-config>=1.2.2,<3.0.0",
    "ovos_bus_client>=2.2.0a1,<3.0.0",
    "ovos-spec-tools>=0.9.0a1",
]

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-cov",
]

[project.urls]
Homepage = "https://github.com/OpenVoiceOS/mycroft-classic-listener"
Repository = "https://github.com/OpenVoiceOS/mycroft-classic-listener"

[project.scripts]
mycroft-classic-listener = "mycroft_classic_listener.__main__:main"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["mycroft_classic_listener*"]

[tool.setuptools.dynamic]
version = {attr = "mycroft_classic_listener.version.__version__"}

[tool.ruff]
exclude = ["_gh_automations", "setup.py"]

[tool.ruff.lint]
select = ["E", "F"]

[tool.pytest.ini_options]
addopts = "--ignore-glob=setup.py"
norecursedirs = ".git build __pycache__ docs"

[tool.coverage.run]
branch = true
source = ["mycroft_classic_listener"]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "raise NotImplementedError",
    "if __name__ == .__main__.:",
]
